export const ADD_FEATURE = "ADD_FEATURE";
export const ADD_FEATURE_CLASS = "ADD_FEATURE_CLASS";
export const DELETE_FEATURE = "DELETE_FEATURE";
export const DELETE_FEATURE_CLASS = "DELETE_FEATURE_CLASS";
